POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Seila evento",
  "details": null,
  "maximumAttendees": 21
}

###

POST http://localhost:3333/events/418334c0-3713-4447-82ac-d2547a442c32/attendees
Content-Type: application/json

{
  "name": "Jose Gonçalvess",
  "email": "alberto.g.a2s@gmail.com"
}

###

GET http://localhost:3333/events/418334c0-3713-4447-82ac-d2547a442c32

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/418334c0-3713-4447-82ac-d2547a442c32/attendees?query=asad